### PR TITLE
GUI using Tkinter

### PR DESCRIPTION
**Pull request by Aaditya1612**
Added GUI using Tkinter

Hey @Maleesha-Dinujaya, please review this PR. If accepted please mark under hacktoberfest-accepted

**Screenshot - 1**
image

**Screenshot - 2**
image

**Screenshot - 3**
image

### CODE REVIEW

**Comment by Maleesha-Dinujaya** [comment]
Nice work

**Comment by Aaditya1612** [comment]
@Maleesha-Dinujaya can you please add hacktoberfest-accepted lable, so that it counts towards my hacktoberfest submission

**Comment by Maleesha-Dinujaya** [comment]
I already added it ??

**Comment by Aaditya1612** [comment]
No, it's not showing. Can you please check once again.

**Comment by Maleesha-Dinujaya** [comment]
Is it ok now??

**Comment by Aaditya1612** [comment]
I think there are some issues. No problem

**Comment by Maleesha-Dinujaya** [comment]
If you in discord plz send me ur user name

**Pull request merged**
